// Define browser globals inline to avoid package resolution issues in CI
const browserGlobals = {
    window: "readonly",
    document: "readonly",
    console: "readonly",
    setTimeout: "readonly",
    setInterval: "readonly",
    clearTimeout: "readonly",
    clearInterval: "readonly",
    fetch: "readonly",
    URL: "readonly",
    URLSearchParams: "readonly",
    FormData: "readonly",
    Event: "readonly",
    CustomEvent: "readonly",
    Element: "readonly",
    HTMLElement: "readonly",
    Node: "readonly",
    NodeList: "readonly",
    navigator: "readonly",
    location: "readonly",
    history: "readonly",
    localStorage: "readonly",
    sessionStorage: "readonly",
    requestAnimationFrame: "readonly",
    cancelAnimationFrame: "readonly",
    MutationObserver: "readonly",
    ResizeObserver: "readonly",
    IntersectionObserver: "readonly",
    Blob: "readonly",
    File: "readonly",
    FileReader: "readonly",
    atob: "readonly",
    btoa: "readonly",
    performance: "readonly",
    alert: "readonly",
    confirm: "readonly",
    prompt: "readonly",
};

export default [
    {
        files: ["**/*.js"],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "script",
            globals: {
                ...browserGlobals,
                Chart: "readonly",
                $: "readonly",
                jQuery: "readonly",
            },
        },
        rules: {
            "no-unused-vars": "warn",
            "no-undef": "error",
        },
    },
];
